### ISSUE TITLE
Handling void elements correctly.

### ISSUE THREAD

**Issue by bdjnk** [ajusa/dekao#3]
There are some small number of [void elements](https://developer.mozilla.org/en-US/docs/Glossary/Void_element) in HTML. In terms of this library they can have no `inner`. Right now these aren't supported correctly.

Let's take the `br` and `hr` tags as an example.

```
let r = render:
  br: say ""
  hr: say ""
echo r
```

This echos the following invalid HTML.

```
<br></br><hr></hr>
```

Browsers (Firefox and Chromium) interpret that as follows.

```
<br><br><hr>
```

So the `hr` behaves correctly, despite being malformed, but the `br` does not.

This library should handle void elements properly and should probably generate XHTML style (`<tag />`) tags for them.

**Comment by ajusa** [comment]
Thanks for the well written issue! Fixed as of 0.0.3, in commit 972a925920501e23cbb8f6c1fba6938413fa9842

**Comment by bdjnk** [comment]
You're very welcome, and thank for the rapid fix. As part of this you tagged `0.0.3`, but in `dekao.nimble` the version number remains `0.0.2`, which can lead to some issues with package management. @ajusa

**Comment by ajusa** [comment]
Sorry about that, I haven't maintained many Nim packages for others to use. Updated both with 0.0.4.
